// ── Typed client factory ────────────────────────────────
// Generic over a collections map, so collection access is type-checked
// without hand-writing interfaces — pair with the codegen CLI output.

import { LazypockClient } from "./lazypock";
import type { CollectionService } from "./collection";
import type { LazypockClientOptions } from "./lazypock";

/**
 * A collections map: `{ posts: PostRecord; users: UserRecord; ... }`.
 * Generated by the codegen CLI (`npx lazypock-gen`) or written by hand.
 */
export type LazypockCollections = Record<string, unknown>;

/**
 * Client typed against a {@link LazypockCollections} map.
 *
 * ```ts
 * import { createClient } from "lazypock/generated";
 * const client = createClient({ baseUrl: "http://localhost:4000/api" });
 * const posts = await client.collection("posts").list<PostsRecord>();
 * ```
 */
export class TypedClient<
	TCollections extends LazypockCollections = LazypockCollections,
> extends LazypockClient {
	/**
	 * Get a typed service for a collection.
	 * When `TCollections` is provided, unknown collection names are rejected.
	 * @typeParam K — Collection name (keyof TCollections).
	 */
	override collection<K extends keyof TCollections>(
		name: K,
	): CollectionService<TCollections[K]>;
	override collection(name: string): CollectionService<unknown> {
		return super.collection(name) as unknown as CollectionService<unknown>;
	}
}

/**
 * Create a {@link TypedClient}.
 * @typeParam TCollections — Map of collection name → record shape.
 */
export function createClient<
	TCollections extends LazypockCollections = LazypockCollections,
>(options: LazypockClientOptions): TypedClient<TCollections> {
	return new TypedClient<TCollections>(options);
}
