// ── Codegen ─────────────────────────────────────────────
// Generates a `lazypock.types.ts` module from the live API schema.
//
// The generated file exports:
//   - One interface per collection (e.g. `PostsRecord`)
//   - A `LazypockCollections` map: { posts: PostsRecord; users: UsersRecord; ... }
//   - A `createClient()` factory pre-bound to those types, so
//     `client.collection("posts").create({ title: "x" })` is fully type-checked.
//
// The CLI in `src/cli.ts` wires this to `GET /collections`.

import type { CollectionSchema, SchemaField } from "./schema";
import { fieldTypeScriptType } from "./typegen";

/** Format a raw collection name into a valid TS identifier (PascalCase). */
export function collectionTypeName(name: string): string {
	return name
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("")
		.replace(/^[0-9]/, "_$&");
}

/** Interface member name — sanitize hyphens/spaces but keep readability. */
export function fieldKey(name: string): string {
	return name.replace(/[^a-zA-Z0-9_]/g, "_");
}



/**
 * Generate the full TypeScript source for the typed SDK module.
 *
 * @param collections Collections fetched from the API.
 * @param options Generation options.
 */
export function generateTypes(
	collections: CollectionSchema[],
	options: {
		/** Import specifier for the lazypock package (default `lazypock`). */
		packageName?: string;
		/** Emit base record fields (id, created, updated, …). Default true. */
		includeBaseFields?: boolean;
		/** Skip system collections (names starting with `_` or `users`). Default false. */
		skipSystem?: boolean;
	} = {},
): string {
	const {
		packageName = "lazypock",
		includeBaseFields = true,
		skipSystem = false,
	} = options;

	const filtered = skipSystem
		? collections.filter(
				(c) => !c.system && !c.name.startsWith("_") && c.name !== "users",
			)
		: collections;

	const sections: string[] = [];
	sections.push(`// ── Auto-generated by lazypock-ts ──────────────────────────
// Do not edit by hand. Regenerate with: npx lazypock-gen
// Schema snapshot: ${new Date().toISOString()}`);

	if (includeBaseFields) {
		sections.push(`export interface BaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}`);
	}

	// One interface per collection
	for (const coll of filtered) {
		const typeName = collectionTypeName(coll.name);
		const fields = coll.fields ?? [];
		const lines = fields.map((f) => memberLine(f)).filter((l) => l !== "");
		const body = lines.join("\n");
		sections.push(
			`export interface ${typeName}Record${renderInterface({
				extends: includeBaseFields ? "BaseRecord" : undefined,
				body,
			})}`,
		);
	}

	// Auth collection type
	sections.push(`export interface AuthRecord extends BaseRecord {
  email: string;
  verified: boolean;
}`);

	// Collections map
	const mapEntries = filtered
		.map(
			(c) =>
				`  "${c.name}": ${collectionTypeName(c.name)}Record${
					c.type === "auth" ? " & AuthRecord" : ""
				};`,
		)
		.join("\n");
	sections.push(`export interface LazypockCollections {
${mapEntries}
}`);

	// createClient factory
	sections.push(`import { LazypockClient, type LazypockClientOptions, type CollectionService } from "${packageName}";

/**
 * Create a Lazypock client typed against this schema snapshot.
 * Collection access is fully type-checked:
 *   client.collection("posts").create({ title: "x" }) // title must exist
 */
export function createClient(options: LazypockClientOptions): TypedClient {
  return new TypedClient(options);
}

export class TypedClient extends LazypockClient {
  override collection<T extends string>(name: T): T extends keyof LazypockCollections
    ? CollectionService<LazypockCollections[T]>
    : CollectionService<unknown> {
    return super.collection(name) as T extends keyof LazypockCollections ? CollectionService<LazypockCollections[T]> : CollectionService<unknown>;
  }
}
`);

	return sections.join("\n\n") + "\n";
}

/**
 * Render the interface body including the extends clause.
 * Empty body → ` extends BaseRecord {}` (valid TS).
 */
function renderInterface(opts: { extends?: string; body: string }): string {
	const ext = opts.extends ? ` extends ${opts.extends}` : "";
	if (!opts.body) return `${ext} {}`;
	return `${ext} {\n${opts.body}\n}`;
}

/** Render a single interface member line for a field. */
function memberLine(f: SchemaField): string {
	const key = fieldKey(f.name);
	const req = f.required || f.type === "password" ? "" : "?";
	const type = fieldTypeScriptType(f);
	// `never` members (passwords) are omitted from read models.
	if (type === "never") return "";
	return `  ${JSON.stringify(key)}${req}: ${type};`;
}
