// ── Codegen ─────────────────────────────────────────────
// Generates a `lazypock.types.ts` module from the live API schema.
//
// The generated file exports:
//   - One interface per collection (e.g. `PostsRecord`)
//   - A `LazypockCollections` map: { posts: PostsRecord; users: UsersRecord; ... }
//   - A `createClient()` factory pre-bound to those types, so
//     `client.collection("posts").create({ title: "x" })` is fully type-checked.
//
// The CLI in `src/cli.ts` wires this to `GET /collections`.

import type { CollectionSchema, SchemaField } from "./schema";
import { fieldTypeScriptType } from "./typegen";

/** Format a raw collection name into a valid TS identifier (PascalCase). */
export function collectionTypeName(name: string): string {
	return name
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("")
		.replace(/^[0-9]/, "_$&");
}

/** Interface member name — sanitize hyphens/spaces but keep readability. */
export function fieldKey(name: string): string {
	return name.replace(/[^a-zA-Z0-9_]/g, "_");
}



/**
 * Generate the full TypeScript source for the typed SDK module.
 *
 * @param collections Collections fetched from the API.
 * @param options Generation options.
 */
export function generateTypes(
	collections: CollectionSchema[],
	options: {
		/** Import specifier for the lazypock package (default `lazypock`). */
		packageName?: string;
		/** Emit base record fields (id, created, updated, …). Default true. */
		includeBaseFields?: boolean;
		/** Skip system collections (names starting with `_` or `users`). Default false. */
		skipSystem?: boolean;
	} = {},
): string {
	const {
		packageName = "lazypock",
		includeBaseFields = true,
		skipSystem = false,
	} = options;

	const filtered = skipSystem
		? collections.filter(
				(c) => !c.system && !c.name.startsWith("_") && c.name !== "users",
			)
		: collections;

	const sections: string[] = [];
	sections.push(`// ── Auto-generated by lazypock-ts ──────────────────────────
// Do not edit by hand. Regenerate with: npx lazypock-gen
// Schema snapshot: ${new Date().toISOString()}`);

	if (includeBaseFields) {
		sections.push(`export interface BaseRecord {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}`);
	}

	// One interface per collection
	for (const coll of filtered) {
		const typeName = collectionTypeName(coll.name);
		const fields = coll.fields ?? [];
		const lines = fields.map((f) => memberLine(f)).filter((l) => l !== "");
		const body = lines.join("\n");
		sections.push(
			`export interface ${typeName}Record${renderInterface({
				extends: includeBaseFields ? "BaseRecord" : undefined,
				body,
			})}`,
		);

		// Write-only create data: what `create()`/`update()` accept. This
		// intentionally includes password fields (and hidden fields) that are
		// excluded from the read model — the server accepts them on write,
		// hashes passwords, and never returns them in responses.
		const createLines: string[] = [];
		const seenKeys = new Set<string>();
		for (const f of fields) {
			for (const { key, line } of createDataMemberLines(f)) {
				if (seenKeys.has(key)) continue;
				seenKeys.add(key);
				createLines.push(line);
			}
		}
		sections.push(
			`export interface ${typeName}CreateData${renderInterface({
				body: createLines.join("\n"),
			})}`,
		);
	}

	// Auth collection type
	sections.push(`export interface AuthRecord extends BaseRecord {
  email: string;
  verified: boolean;
}`);

	// Collections map
	const mapEntries = filtered
		.map(
			(c) =>
				`  "${c.name}": ${collectionTypeName(c.name)}Record${
					c.type === "auth" ? " & AuthRecord" : ""
				};`,
		)
		.join("\n");
	sections.push(`export interface LazypockCollections {
${mapEntries}
}`);

	// Create-data map — typed `create()`/`update()` payloads, including
	// write-only password fields.
	const createMapEntries = filtered
		.map((c) => `  "${c.name}": ${collectionTypeName(c.name)}CreateData;`)
		.join("\n");
	sections.push(`export interface LazypockCreateData {
${createMapEntries}
}`);

	// Runtime schema snapshot — lets the client exclude hidden fields by
	// default, validate select/expand, and derive visible field lists.
	const schemaEntries = collections
		.map(
			(c) =>
				`  {
    id: ${JSON.stringify(c.id ?? null)},
    name: ${JSON.stringify(c.name)},
    type: ${JSON.stringify(c.type)},
    system: ${JSON.stringify(c.system ?? false)},
    fields: ${JSON.stringify(c.fields ?? [], null, 2)},
    rules: ${JSON.stringify(c.rules ?? {})},
    options: ${JSON.stringify(c.options ?? {})},
  }`,
		)
		.join(",\n");
	sections.push(`// Schema snapshot (runtime) — hidden-field exclusion + query validation.
export const lazypockSchema: import("${packageName}").CollectionSchema[] = [
${schemaEntries}
];`);

	// createClient factory
	sections.push(`import { LazypockClient, type LazypockClientOptions, type CollectionService } from "${packageName}";

/**
 * Create a Lazypock client typed against this schema snapshot.
 * Collection access is fully type-checked:
 *   client.collection("posts").create({ title: "x" }) // title must exist
 *
 * For auth collections the generated *CreateData type includes the
 * write-only password field, so creating a user is type-safe:
 *   client.collection("users").create({ email, password }) // ✓
 *
 * The schema snapshot is wired into the client automatically, so hidden
 * fields are excluded from responses and select/expand are validated.
 */
export function createClient(options: LazypockClientOptions): TypedClient {
  return new TypedClient({
    ...options,
    types: {
      ...options.types,
      schemas: options.types?.schemas ?? lazypockSchema,
    },
  });
}

export class TypedClient extends LazypockClient {
  // The constraint is "keyof LazypockCollections | (string & {})" rather than a
  // bare generic string or a strict keyof:
  //   - the keyof LazypockCollections member is what makes the IDE suggest
  //     collection names, and known literals resolve to the typed service:
  //       client.collection("posts")  // suggested + typed
  //   - the string & {} member keeps unknown/dynamic names compiling — they
  //     resolve to the untyped service, so a studio that manages
  //     user-created collections can still call collection(someString).
  //
  // The (string & {}) intersection keeps the union from collapsing to plain
  // string (which would silently kill the suggestions).
  //
  // create()/update() take the collection's *CreateData — the read model
  // omits password/hidden fields, but the write model carries them.
  override collection<K extends keyof LazypockCollections | (string & {})>(
    name: K,
  ): K extends keyof LazypockCollections
    ? CollectionService<LazypockCollections[K], LazypockCreateData[K]>
    : CollectionService<unknown> {
    return super.collection(name) as K extends keyof LazypockCollections
      ? CollectionService<LazypockCollections[K], LazypockCreateData[K]>
      : CollectionService<unknown>;
  }
}
`);

	return sections.join("\n\n") + "\n";
}

/**
 * Render the interface body including the extends clause.
 * Empty body → ` extends BaseRecord {}` (valid TS).
 */
function renderInterface(opts: { extends?: string; body: string }): string {
	const ext = opts.extends ? ` extends ${opts.extends}` : "";
	if (!opts.body) return `${ext} {}`;
	return `${ext} {\n${opts.body}\n}`;
}

/** Render a single interface member line for a field. */
function memberLine(f: SchemaField): string {
	// Hidden fields are excluded from API responses by the schema-aware
	// client default — don't expose them on the read model either.
	if (f.hidden) return "";
	const key = fieldKey(f.name);
	const req = f.required || f.type === "password" ? "" : "?";
	const type = fieldTypeScriptType(f);
	// `never` members (passwords) are omitted from read models.
	if (type === "never") return "";
	return `  ${JSON.stringify(key)}${req}: ${type};`;
}

/**
 * Render the write-only create-data members for a field.
 *
 * Unlike the read model, create/update data includes password fields (sent as
 * plain strings — the server hashes them) and hidden fields: the server
 * accepts them on write and never returns them in responses.
 *
 * Password fields are exposed under the canonical PocketBase API key
 * `password` (the server accepts `password` for any single password field and
 * hashes it into the backing column, e.g. `password_hash`), with the raw
 * metadata name kept as a backward-compat alias.
 *
 * A field is only marked required when it actually needs a client value:
 * fields with a server-side default (`options.defaultValue`) and the auth
 * system fields `verified` / `emailVisibility` (the server defaults them to
 * false/true even though the snapshot doesn't carry `defaultValue`) stay
 * optional, so `create({ email, password })` typechecks without forcing
 * callers to send values the server would fill in anyway. Password fields
 * are optional (accounts may exist without a password, e.g. OAuth-only).
 */
function createDataMemberLines(
	f: SchemaField,
): { key: string; line: string }[] {
	// Autodate columns are server-managed; never writable.
	if (f.type === "autodate") return [];
	const rawName = fieldKey(f.name);
	const serverDefaulted =
		f.options?.defaultValue !== undefined ||
		(f.system && (f.name === "verified" || f.name === "emailVisibility"));
	const req = f.required && !serverDefaulted ? "" : "?";
	const type = f.type === "password" ? "string" : fieldTypeScriptType(f);
	if (type === "never") return [];

	const members = [
		{ key: rawName, line: `  ${JSON.stringify(rawName)}${req}: ${type};` },
	];
	// Write-only password: canonical key is `password` (PocketBase parity) —
	// the server accepts `password` for any single password field and hashes
	// it. The raw metadata name (e.g. `password_hash`) stays as a compat alias.
	if (f.type === "password" && rawName !== "password") {
		members.unshift({
			key: "password",
			line: `  ${JSON.stringify("password")}${req}: ${type};`,
		});
	}
	return members;
}
